apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  resources:
    - name: git-source
      type: git
  tasks:
    - name: build-task
      taskRef:
        name: build-task
      resources:
        inputs:
        - name: git-source
          resource: git-source
